on:
  push:
    branches:
      - 'build-*'
    tags: '*'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'website/**'

jobs:
  trigger-release:
    name: Trigger Installers Build
    runs-on: self-hosted
    needs: build-gem
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Create Installers Release
        run: ./.ci/release.sh
        working-directory: ${{github.workspace}}
      - name: Clean Workspace
        if: always()
        run: rm -rf ${{ github.workspace }}
